### ISSUE TITLE
Still see "User has not accepted EULA .." for users coming from the Dan Mardsen plugin

### ISSUE THREAD

**Issue by hitteshahuja** [jmcgettrick/moodle-plagiarism_turnitin#11]
Hi John,
I believe you did aim to fix this but unfortunately this is still an issue. After upgrading the plugin from Dan Mardsen to mod_plagiarism_turnitin, for students that have never submitted using the new API, they get this : 
![moodle26-blank- administration- plugins- plagiarism- turnitin plagiarism plugin](https://cloud.githubusercontent.com/assets/2855029/8877525/cf521d30-321d-11e5-8778-8c95d72f0086.gif)

I thought your fixes 5b21e213313dd698dad32c46423e3245d84d69a3 and 97962b52d9c52d382e7285d95e34fa75533a62b0 would tackle this and show student similarity reports retrospectively from the old plugin ?

Regards,
Hittesh

**Comment by hitteshahuja** [comment]
I think what was missing... when running the upgrade_dm_successful_uploads() function from db/upgrade.php that you introduced here 0cc0f76a49c2e5579b3082ea54153033e9b83e98 ,you should also make sure that sucessfull submissions are shown by modifying the lastmodified date just like you did for status =51 . 
So it should contain an additional execute : 

$DB->execute("UPDATE ".$CFG->prefix."plagiarism_turnitin_files SET  lastmodified = ".time()." WHERE statuscode = 'success'");

**Comment by jmcgettrick** [comment]
This has now been released.

**Comment by hitteshahuja** [comment]
Hi John, Many thanks for your fix. 

Although your fix has covered 'success' and 51 status codes... it still shows up 'EULA not accepted' for any other status code types.

For our database, we see the following status codes generating the 'EULA' error message where in-fact they are error messages for different reasons: 
1001
1009
1023
1007
250
220
1000
11
31
2108
1019
1013
1024
1011
200
423
213
218
424
127
204
432
206
212
51
228
217
248
221
216
1012

These errors are documented on the following page on Moodle and were part of Dan Marsden plugin lang file 
https://docs.moodle.org/dev/Turnitin_errors?redirect=no

https://github.com/danmarsden/moodle-plagiarism_turnitin/blob/master/lang/en/plagiarism_turnitin.php

It would be great if you could incorporate these in your fix so that the appropriate error message is shown for each error code.

Thanks,
Hittesh

**Comment by jmcgettrick** [comment]
The API that is used by this plugin doesn't return error codes, these error codes are specific to the legacy API used by our v1 plugin and Dan's plugin.

**Comment by hitteshahuja** [comment]
Ok. So how do you suggest we make it work on the new plugin as part of the
migration from APIv1 to APIv2?

Regards,
Hittesh

**Comment by jmcgettrick** [comment]
We don't see it as an issue as these files haven't gone to Turnitin. If they were resubmitted the plugin wouldn't even attempt to send them to Turnitin because the EULA hasn't been accepted by the student. Effectively it is the main or most important error because the user can not use Turnitin functionality without accepting the EULA.

**Comment by hitteshahuja** [comment]
Thank you for your feedback. Is there a way I could raise this on the turnitin's feature request page ( can't remember what its called) as a new suggestion to make debugging helpful for admins.

Regards,
Hittesh

**Comment by cwestgarth** [comment]
Hi @hitteshahuja 
Yes you can submit your idea to Uservoice. You can access Uservoice by logging into www.turnitinuk.com and selecting roadmap. 

Thanks
