### ISSUE TITLE
Add the "Student has viewed feedback" indicator to PP also.

### ISSUE THREAD

**Issue by mkpelletier** [jmcgettrick/moodle-plagiarism_turnitin#15]
In Turnitintool 1 & 2, there is an indicator to show that a student has reviewed the feedback on an assignment.  This appears to be missing from the Plagiarism Plugin.  It would be useful if we could also integrate this into the course events monitoring as well.  If the field is made available via the moodle DB, it would be useful for setting course completion restrictions based on whether feedback has been viewed.

**Comment by jmcgettrick** [comment]
This is about to be released in 2015040110. Please note that repository has moved to the Turnitin account at: https://github.com/turnitin/moodle-plagiarism_turnitin
