### ISSUE TITLE
Changing grade for previous attempt overwrites correct value

### ISSUE THREAD

**Issue by micaherne** [jmcgettrick/moodle-plagiarism_turnitin#22]
Hi John, we're testing 2015040107 for the multiple attempts issue we reported in https://github.com/jmcgettrick/MoodleDirectV2/issues/442, and it's working much better - thanks for fixing it - but we've discovered there's still a small bug where the wrong value is being overwritten. It only happens if someone changes a mark for a previous attempt in Grademark, so it's maybe not a big problem, but it's definitely not working correctly.

To reproduce it (as an admin who is also enrolled on the course as a student):

1. Submit an assignment, wait until it's uploaded to Turnitin, then go into Grademark to mark it - give it 12 marks. Close Grademark and wait for the submission page to update.
2. Go back to Moodle and allow a second attempt. Submit the second attempt, wait until it's sent to Turnitin then open Grademark to mark it - give it 24 marks. Close Grademark and wait for the submission page to update. (Everything is working perfectly up to here) 
3. In the "all submissions" page, click on the grading icon to go to the Moodle grading page. Go into Grademark for the first attempt, and change the mark to 13. Close Grademark and wait for the submission page to update.

You'll find that the changed mark for the first attempt has overwritten the mark for the second attempt in both the grading page and the "all submissions" page (so the user's grade has gone from 24 to 13).

**Comment by jmcgettrick** [comment]
We'll get this looked at Michael.

**Comment by jmcgettrick** [comment]
This has been fixed with v2015040109.

**Comment by micaherne** [comment]
Excellent, thanks John!
