### ISSUE TITLE
Due dates on Forums

### ISSUE THREAD

**Issue by mkpelletier** [jmcgettrick/moodle-plagiarism_turnitin#8]
The plagiarism plugin on forums needs some way of setting a due date.  We have several instances of students attempting to post to a forum and receiving the message:
"Turnitin has returned an error with your submission: The due date for this assignment has passed and you have already made a submission."

Furthermore, since forums typically consist of multiple submissions by the same student, the error message generates confusion.  I have had to disable Tii on our forums until the issue is resolved.

We are using Moodle 2.8.6+ (Build: 20150625) and Tii PP 2015040106.

**Comment by daparker26** [comment]
@mkpelletier Having the same issue here.

**Comment by jmcgettrick** [comment]
This has been fixed with release 2015040109.
